name: Integration Test Build for Activity API

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "15 9 * * *"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    #Steps:
    #Clone the project/repository
    #Setup the Python environment
    #Install dependencies which are in requirements.txt
    #pytest with HTML test report
    #Check if tests are passing or failing and upload the test report
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          pytest

      - name: Upload Test HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ./reports/report*.html
